module.exports = {
  sidebars:{
    'Getting Started': [
      'Overview/Welcome',
      //'Overview/IntakeRepLinks', 
      //'Overview/SchedulerLinks',
     ],
  //   'Admin Setup': [
  //   'AdminSetup/Account', 
  //   'AdminSetup/BusinessUnit',
  //   'AdminSetup/GoalBankLibrary',
  //   'AdminSetup/HealthcareService',
  //   'AdminSetup/InsurancePlan',
  //   'AdminSetup/Location',
  //   'AdminSetup/QualificationDefinition',
  // ],
  // 'Clinical Setup':[
  //   'ClinicalSetup/Authorizations',
  //   'ClinicalSetup/CareTeamAssignment',
  //   'ClinicalSetup/Coverage',
  //   'ClinicalSetup/Contacts',
  // ],
  'Patients':[
    'Patients/PatientOverview',
    'Patients/Location',
    'Patients/Connection',
    'Patients/ConnectionRole',
    'Patients/Conditions',
    'Patients/EpisodeOfCare',
    'Patients/Coverages',
    'Patients/Authorization',
    'Patients/AuthorizationServices',
    'Patients/CareTeamParticipants',
    'Patients/CareTeamAssignments',
    'Patients/PatientEncounters',
    'Patients/PatientCalendar',
  ],
  'Practitioners':[
    'Practitioners/BasicInfo',
    'Practitioners/PractitionerRole',    
    'Practitioners/Qualifications',
    'Practitioners/CareTeamAssignment',
    'Practitioners/PractitionerEncounters',
    'Practitioners/PractitionerCalendar',

   ],
 'Scheduling':[
  'Encounters/SingleEncounters',
  'Encounters/RecurringEncounters',
    'Encounters/EncounterValidations',
    'Scheduling/ScheduleAssistance',
    'Encounters/DeactivateEncounters',
 ],
  },
};